version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_API_BASE_URL=${BACKEND_API_BASE_URL}
    ports:
      - "3000:80"
    environment:
      - BACKEND_API_BASE_URL=${BACKEND_API_BASE_URL}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
        - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        - GOOGLE_DISCOVERY_URL=${GOOGLE_DISCOVERY_URL}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    ports:
      - "8080:8080"
    environment:
        - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
        - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        - GOOGLE_DISCOVERY_URL=${GOOGLE_DISCOVERY_URL}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
