version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - mock-ecommerce-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - mock-ecommerce-network
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - mock-ecommerce-network

networks:
  mock-ecommerce-network:
    driver: bridge
