spring:
    datasource:
        url: jdbc:h2:mem:mydb
        username: user
        password:
        driverClassName: org.h2.Driver
        generate-unique-name: false
        name: factory
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
